export const LOGIN_WITH_EMAIL_ACTION_TYPES = {
  LOGIN_WITH_EMAIL_REQUEST: "LOGIN_WITH_EMAIL_REQUEST",
  LOGIN_WITH_EMAIL_FULFILLED: "LOGIN_WITH_EMAIL_FULFILLED",
  LOGIN_WITH_EMAIL_REJECTED: "LOGIN_WITH_EMAIL_REJECTED"
};

export const SOCIAL_LOGIN_ACTION_TYPES = {
  SOCIAL_LOGIN_REQUEST: "SOCIAL_LOGIN_REQUEST",
  SOCIAL_LOGIN_FULFILLED: "SOCIAL_LOGIN_FULFILLED",
  SOCIAL_LOGIN_REJECTED: "SOCIAL_LOGIN_REJECTED"
};

export const FETCH_USER_ACTION_TYPES = {
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_FULFILLED: "FETCH_USER_FULFILLED",
  FETCH_USER_REJECTED: "FETCH_USER_REJECTED"
};

export const SIGHUP_WITH_EMAIL_ACTION_TYPES = {
  SIGNUP_WITH_EMAIL_REQUEST: "SIGNUP_WITH_EMAIL_REQUEST",
  SIGNUP_WITH_EMAIL_FULFILLED: "SIGNUP_WITH_EMAIL_FULFILLED",
  SIGNUP_WITH_EMAIL_REJECTED: "SIGNUP_WITH_EMAIL_REJECTED"
}

export const GET_CAMPAIGN_TYPE_ACTION_TYPES = {
  GET_CAMPAIGN_TYPE_REQUEST: "GET_CAMPAIGN_TYPE_REQUEST",
  GET_CAMPAIGN_TYPE_FULFILLED: "GET_CAMPAIGN_TYPE_FULFILLED",
  GET_CAMPAIGN_TYPE_REJECTED: "GET_CAMPAIGN_TYPE_REJECTED"
}

export const GET_CAMPAIGN_CATEGORIES_ACTION_TYPES = {
  GET_CAMPAIGN_CATEGORIES_REQUEST: "GET_CAMPAIGN_CATEGORIES_REQUEST",
  GET_CAMPAIGN_CATEGORIES_FULFILLED: "GET_CAMPAIGN_CATEGORIES_FULFILLED",
  GET_CAMPAIGN_CATEGORIES_REJECTED: "GET_CAMPAIGN_CATEGORIES_REJECTED"
}

export const GET_CAMPAIGN_STRATEGY_ACTION_TYPES = {
  GET_CAMPAIGN_STRATEGY_REQUEST: "GET_CAMPAIGN_STRATEGY_REQUEST",
  GET_CAMPAIGN_STRATEGY_FULFILLED: "GET_CAMPAIGN_STRATEGY_FULFILLED",
  GET_CAMPAIGN_STRATEGY_REJECTED: "GET_CAMPAIGN_STRATEGY_REJECTED"
}

export const CAMPAIGN_CREATE_ACTION_TYPES = {
  CAMPAIGN_CREATE_REQUEST: "CAMPAIGN_CREATE_REQUEST",
  CAMPAIGN_CREATE_FULFILLED: "CAMPAIGN_CREATE_FULFILLED",
  CAMPAIGN_CREATE_REJECTED: "CAMPAIGN_CREATE_REJECTED"
}

export const GET_CAMPAIGN_ACTIVE_ACTION_TYPES = {
  GET_CAMPAIGN_ACTIVE_REQUEST: "GET_CAMPAIGN_ACTIVE_REQUEST",
  GET_CAMPAIGN_ACTIVE_FULFILLED: "GET_CAMPAIGN_ACTIVE_FULFILLED",
  GET_CAMPAIGN_ACTIVE_REJECTED: "GET_CAMPAIGN_ACTIVE_REJECTED"
}

export const GET_CAMPAIGN_ACTIVE_MORE_ACTION_TYPES = {
  GET_CAMPAIGN_ACTIVE_MORE_REQUEST: "GET_CAMPAIGN_ACTIVE_MORE_REQUEST",
  GET_CAMPAIGN_ACTIVE_MORE_FULFILLED: "GET_CAMPAIGN_ACTIVE_MORE_FULFILLED",
  GET_CAMPAIGN_ACTIVE_MORE_REJECTED: "GET_CAMPAIGN_ACTIVE_MORE_REJECTED"
}

export const GET_PROFILE_ACTION_TYPES = {
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_FULFILLED: "GET_PROFILE_FULFILLED",
  GET_PROFILE_REJECTED: "GET_PROFILE_REJECTED"
}

export const GET_CAMPAIGN_GOAL_ACTION_TYPES = {
  GET_CAMPAIGN_GOAL_REQUEST: "GET_CAMPAIGN_GOAL_REQUEST",
  GET_CAMPAIGN_GOAL_FULFILLED: "GET_CAMPAIGN_GOAL_FULFILLED",
  GET_CAMPAIGN_GOAL_REJECTED: "GET_CAMPAIGN_GOAL_REJECTED"
}

export const CREATE_CAMPAIGN_GOAL_ACTION_TYPES = {
  CREATE_CAMPAIGN_GOAL_REQUEST: "CREATE_CAMPAIGN_GOAL_REQUEST",
  CREATE_CAMPAIGN_GOAL_FULFILLED: "CREATE_CAMPAIGN_GOAL_FULFILLED",
  CREATE_CAMPAIGN_GOAL_REJECTED: "CREATE_CAMPAIGN_GOAL_REJECTED"
}

export const GET_CAMPAIGN_PRIZE_ACTION_TYPES = {
  GET_CAMPAIGN_PRIZE_REQUEST: "GET_CAMPAIGN_PRIZE_REQUEST",
  GET_CAMPAIGN_PRIZE_FULFILLED: "GET_CAMPAIGN_PRIZE_FULFILLED",
  GET_CAMPAIGN_PRIZE_REJECTED: "GET_CAMPAIGN_PRIZE_REJECTED"
}

export const CREATE_CAMPAIGN_PRIZE_ACTION_TYPES = {
  CREATE_CAMPAIGN_PRIZE_REQUEST: "CREATE_CAMPAIGN_PRIZE_REQUEST",
  CREATE_CAMPAIGN_PRIZE_FULFILLED: "CREATE_CAMPAIGN_PRIZE_FULFILLED",
  CREATE_CAMPAIGN_PRIZE_REJECTED: "CREATE_CAMPAIGN_PRIZE_REJECTED"
}

export const UPDATE_CAMPAIGN_PRIZE_ACTION_TYPES = {
  UPDATE_CAMPAIGN_PRIZE_REQUEST: "UPDATE_CAMPAIGN_PRIZE_REQUEST",
  UPDATE_CAMPAIGN_PRIZE_FULFILLED: "UPDATE_CAMPAIGN_PRIZE_FULFILLED",
  UPDATE_CAMPAIGN_PRIZE_REJECTED: "UPDATE_CAMPAIGN_PRIZE_REJECTED"
}

export const DELETE_CAMPAIGN_PRIZE_ACTION_TYPES = {
  DELETE_CAMPAIGN_PRIZE_REQUEST: "DELETE_CAMPAIGN_PRIZE_REQUEST",
  DELETE_CAMPAIGN_PRIZE_FULFILLED: "DELETE_CAMPAIGN_PRIZE_FULFILLED",
  DELETE_CAMPAIGN_PRIZE_REJECTED: "DELETE_CAMPAIGN_PRIZE_REJECTED"
}

export const PUBLISH_CAMPAIGN_ACTION_TYPES = {
  PUBLISH_CAMPAIGN_REQUEST: "PUBLISH_CAMPAIGN_REQUEST",
  PUBLISH_CAMPAIGN_FULFILLED: "PUBLISH_CAMPAIGN_FULFILLED",
  PUBLISH_CAMPAIGN_REJECTED: "PUBLISH_CAMPAIGN_REJECTED"
}

export const GET_CAMPAIGN_ACTION_TYPES = {
  GET_CAMPAIGN_REQUEST: "GET_CAMPAIGN_REQUEST",
  GET_CAMPAIGN_FULFILLED: "GET_CAMPAIGN_FULFILLED",
  GET_CAMPAIGN_REJECTED: "GET_CAMPAIGN_REJECTED"
}

export const GET_QUIZ_ACTION_TYPES = {
  GET_QUIZ_REQUEST: "GET_QUIZ_REQUEST",
  GET_QUIZ_FULFILLED: "GET_QUIZ_FULFILLED",
  GET_QUIZ_REJECTED: "GET_QUIZ_REJECTED" 
}

export const GET_QUIZ_QUESTION_ACTION_TYPES = {
  GET_QUIZ_QUESTION_REQUEST: "GET_QUIZ_QUESTION_REQUEST",
  GET_QUIZ_QUESTION_FULFILLED: "GET_QUIZ_QUESTION_FULFILLED",
  GET_QUIZ_QUESTION_REJECTED: "GET_QUIZ_QUESTION_REJECTED" 
}

export const POST_ANSWER_ACTION_TYPES = {
  POST_ANSWER_REQUEST: "POST_ANSWER_REQUEST",
  POST_ANSWER_FULFILLED: "POST_ANSWER_FULFILLED",
  POST_ANSWER_REJECTED: "POST_ANSWER_REJECTED" 
}

export const SUBMIT_QUIZ_ACTION_TYPES = {
  SUBMIT_QUIZ_REQUEST: "SUBMIT_QUIZ_REQUEST",
  SUBMIT_QUIZ_FULFILLED: "SUBMIT_QUIZ_FULFILLED",
  SUBMIT_QUIZ_REJECTED: "SUBMIT_QUIZ_REJECTED"
}

export const PAYMENT_ACTION_TYPES = {
  PAYMENT_REQUEST: "PAYMENT_REQUEST",
  PAYMENT_FULFILLED: "PAYMENT_FULFILLED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED"
}

export const GET_WALLET_BALANCE_ACTION_TYPES = {
  GET_WALLET_BALANCE_REQUEST: "GET_WALLET_BALANCE_REQUEST",
  GET_WALLET_BALANCE_FULFILLED: "GET_WALLET_BALANCE_FULFILLED",
  GET_WALLET_BALANCE_REJECTED: "GET_WALLET_BALANCE_REJECTED"
}

export const WALLET_TOPUP_ACTION_TYPES = {
  WALLET_TOPUP_REQUEST: "WALLET_TOPUP_REQUEST",
  WALLET_TOPUP_FULFILLED: "WALLET_TOPUP_FULFILLED",
  WALLET_TOPUP_REJECTED: "WALLET_TOPUP_REJECTED"
}

export const SAVE_CAMPAIGN_ACTION_TYPES = {
  SAVE_CAMPAIGN_REQUEST: "SAVE_CAMPAIGN_REQUEST",
  SAVE_CAMPAIGN_FULFILLED: "SAVE_CAMPAIGN_FULFILLED",
  SAVE_CAMPAIGN_REJECTED: "SAVE_CAMPAIGN_REJECTED"
}

export const DONATION_ACTION_TYPES = {
  DONATION_REQUEST: "DONATION_REQUEST",
  DONATION_FULFILLED: "DONATION_FULFILLED",
  DONATION_REJECTED: "DONATION_REJECTED"
}

export const GET_SAVED_ACTION_TYPES = {
  GET_SAVED_REQUEST: "GET_SAVED_REQUEST",
  GET_SAVED_FULFILLED: "GET_SAVED_FULFILLED",
  GET_SAVED_REJECTED: "GET_SAVED_REJECTED"
}

export const GET_SAVED_MORE_ACTION_TYPES = {
  GET_SAVED_MORE_REQUEST: "GET_SAVED_MORE_REQUEST",
  GET_SAVED_MORE_FULFILLED: "GET_SAVED_MORE_FULFILLED",
  GET_SAVED_MORE_REJECTED: "GET_SAVED_MORE_REJECTED"
}

export const GET_ENDED_ACTION_TYPES = {
  GET_ENDED_REQUEST: "GET_ENDED_REQUEST",
  GET_ENDED_FULFILLED: "GET_ENDED_FULFILLED",
  GET_ENDED_REJECTED: "GET_ENDED_REJECTED"
}

export const GET_ENDED_MORE_ACTION_TYPES = {
  GET_ENDED_MORE_REQUEST: "GET_ENDED_MORE_REQUEST",
  GET_ENDED_MORE_FULFILLED: "GET_ENDED_MORE_FULFILLED",
  GET_ENDED_MORE_REJECTED: "GET_ENDED_MORE_REJECTED"
}

export const GET_DONATIONS_ACTION_TYPES = {
  GET_DONATIONS_REQUEST: "GET_DONATIONS_REQUEST",
  GET_DONATIONS_FULFILLED: "GET_DONATIONS_FULFILLED",
  GET_DONATIONS_REJECTED: "GET_DONATIONS_REJECTED"
}

export const GET_DONATIONS_MORE_ACTION_TYPES = {
  GET_DONATIONS_MORE_REQUEST: "GET_DONATIONS_MORE_REQUEST",
  GET_DONATIONS_MORE_FULFILLED: "GET_DONATIONS_MORE_FULFILLED",
  GET_DONATIONS_MORE_REJECTED: "GET_DONATIONS_MORE_REJECTED"
}

export const GET_COUNTRIES_ACTION_TYPES = {
  GET_COUNTRIES_REQUEST: "GET_COUNTRIES_REQUEST",
  GET_COUNTRIES_FULFILLED: "GET_COUNTRIES_FULFILLED",
  GET_COUNTRIES_REJECTED: "GET_COUNTRIES_REJECTED"
}

export const PROFILE_UPDATE_ACTION_TYPES = {
  PROFILE_UPDATE_REQUEST: "PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_FULFILLED: "PROFILE_UPDATE_FULFILLED",
  PROFILE_UPDATE_REJECTED: "PROFILE_UPDATE_REJECTED"
}

export const GAMES_PLAYED_ACTION_TYPES = {
  GAMES_PLAYED_REQUEST: "GAMES_PLAYED_REQUEST",
  GAMES_PLAYED_FULFILLED: "GAMES_PLAYED_FULFILLED",
  GAMES_PLAYED_REJECTED: "GAMES_PLAYED_REJECTED"
}
